Create SQL files PR
mertkantaroglu/Vet-Clinic pull request #1
Opened 2023-04-10 19:09 UTC by mertkantaroglu

Hello,

In this project I created vet_clinic database and animals table. Afterward I populated the SQL files per requirements and took screenshots of queries.

Thanks.

![Screen Shot 2023-04-10 at 17 37 35](https://user-images.githubusercontent.com/44959066/230976575-8f47d81c-8fb0-44a6-b0bb-6be447039ceb.png)
![Screen Shot 2023-04-10 at 18 14 34](https://user-images.githubusercontent.com/44959066/230976654-d0bec667-e162-4999-b2bc-0450cb888d75.png)
![Screen Shot 2023-04-10 at 18 19 45](https://user-images.githubusercontent.com/44959066/230976659-0648c82d-c455-4f38-9221-d65680569924.png)
![Screen Shot 2023-04-10 at 18 19 55](https://user-images.githubusercontent.com/44959066/230976667-55e834d6-ab78-4858-aba0-7d185e43127e.png)

2023-04-10 19:29 UTC, CollinsTatang requested changes
Hi @mertkantaroglu, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- You have properly implement the different queries as per the project requirement :heavy_check_mark: 

## Required changes 
It's ok to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips that can improve your code quality and help you get a better job.
_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-10 19:29 UTC, CollinsTatang commented on README.md
> +This project is [MIT](LICENSE) licensed.
- [ ] Please fix the link to your `LICENSE` file the current link is broken.

2023-04-11 04:49 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @mertkantaroglu ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️
- Good commit messages ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-11 05:04 UTC, mertkantaroglu commented
Thank you @1GORDON 👍

2023-04-12 10:40 UTC, merged